cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = i18n_patterns(
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path(_('admin/'), admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _


app_name = 'orders'

urlpatterns = [
    path(_('create/'), views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label=_('Количество'))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    products = Product.objects.filter(available=True)
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'products': products})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}{% trans "Ваша корзина" %}{% endblock %}
{% block content %}
  <h1>{% trans "Ваша корзина" %}</h1>
  <table class="cart">
    <thead>
      <tr>
        <th></th>
        <th>{% trans "Товар" %}</th>
        <th>{% trans "Количество" %}</th>
        <th>{% trans "Удалить" %}</th>
        <th>{% trans "Цена за еденицу" %}</th>
        <th>{% trans "Итого" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}">
               </a>
             </td>
             <td>{{ product.name }}</td>
             <td>
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="{% trans "Обновить" %}">
                    {% csrf_token %}
                </form>                                
             </td>
             <td><a href="{% url 'cart:cart_remove' product.id%}">{% trans "Удалить" %}</a></td>
             <td class="num">{{ item.price }} руб.</td>
             <td class="num">{{ item.total_price }} руб.</td>
           </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
  <tr class="subtotal">
    <td>{% trans "Подытог" %}</td>
    <td colspan="4"></td>
    <td class="num">{{ cart.get_total_price|floatformat:"2" }} руб.</td>
  </tr>
  <tr>
    {% blocktrans with code=cart.coupon.code discount=cart.coupon.discount %}
    <td>"купон {{ code }}" скидка ({{ discount }}%)</td>
    {% endblocktrans %}
    <td colspan="4"></td>
    <td class="num neg">
      - {{ cart.get_discount|floatformat:"2" }} руб.
    </td>
  </tr>
{% endif %}
<tr class="total">
  <td>{% trans "Итого" %}</td>
  <td colspan="4"></td>
  <td class="num">
    {{ cart.get_total_price_after_discount|floatformat:"2" }} руб.
  </td>
</tr>

    </tbody>
  </table>

  {% if product.category.slug != 'upsales' %}
    <div class="recommendations cart">
      <h3>{% trans "Люди часто также покупают" %}</h3>
      {% for product in products %}
        {% if product.category.slug == 'upsales' %}
          <div class="item">
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
            <p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  {% endif %}

  <p class="text-right">{% trans "Использовать купон" %}:</p>
<form class="text-right" action="{% url "coupons:apply" %}" method="post">
  {{ coupon_apply_form }}
  <input type="submit" value="{% trans "Применить" %}">
  {% csrf_token %}
</form>

  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">{% trans "Продолжить покупки" %}</a>
    <a href="{% url 'orders:order_create' %}" class="button">{% trans "Оформить заказ" %}</a>
  </p>
{% endblock %}